// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/taythebot/discord_chatbot/ent/blacklist"
)

// BlacklistCreate is the builder for creating a Blacklist entity.
type BlacklistCreate struct {
	config
	mutation *BlacklistMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (bc *BlacklistCreate) SetUserID(s string) *BlacklistCreate {
	bc.mutation.SetUserID(s)
	return bc
}

// SetReason sets the "reason" field.
func (bc *BlacklistCreate) SetReason(s string) *BlacklistCreate {
	bc.mutation.SetReason(s)
	return bc
}

// SetCreatedAt sets the "created_at" field.
func (bc *BlacklistCreate) SetCreatedAt(t time.Time) *BlacklistCreate {
	bc.mutation.SetCreatedAt(t)
	return bc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bc *BlacklistCreate) SetNillableCreatedAt(t *time.Time) *BlacklistCreate {
	if t != nil {
		bc.SetCreatedAt(*t)
	}
	return bc
}

// SetUpdatedAt sets the "updated_at" field.
func (bc *BlacklistCreate) SetUpdatedAt(t time.Time) *BlacklistCreate {
	bc.mutation.SetUpdatedAt(t)
	return bc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (bc *BlacklistCreate) SetNillableUpdatedAt(t *time.Time) *BlacklistCreate {
	if t != nil {
		bc.SetUpdatedAt(*t)
	}
	return bc
}

// Mutation returns the BlacklistMutation object of the builder.
func (bc *BlacklistCreate) Mutation() *BlacklistMutation {
	return bc.mutation
}

// Save creates the Blacklist in the database.
func (bc *BlacklistCreate) Save(ctx context.Context) (*Blacklist, error) {
	bc.defaults()
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BlacklistCreate) SaveX(ctx context.Context) *Blacklist {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BlacklistCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BlacklistCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BlacklistCreate) defaults() {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		v := blacklist.DefaultCreatedAt()
		bc.mutation.SetCreatedAt(v)
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		v := blacklist.DefaultUpdatedAt()
		bc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BlacklistCreate) check() error {
	if _, ok := bc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Blacklist.user_id"`)}
	}
	if v, ok := bc.mutation.UserID(); ok {
		if err := blacklist.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Blacklist.user_id": %w`, err)}
		}
	}
	if _, ok := bc.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "Blacklist.reason"`)}
	}
	if v, ok := bc.mutation.Reason(); ok {
		if err := blacklist.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "Blacklist.reason": %w`, err)}
		}
	}
	if _, ok := bc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Blacklist.created_at"`)}
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Blacklist.updated_at"`)}
	}
	return nil
}

func (bc *BlacklistCreate) sqlSave(ctx context.Context) (*Blacklist, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BlacklistCreate) createSpec() (*Blacklist, *sqlgraph.CreateSpec) {
	var (
		_node = &Blacklist{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(blacklist.Table, sqlgraph.NewFieldSpec(blacklist.FieldID, field.TypeInt))
	)
	_spec.OnConflict = bc.conflict
	if value, ok := bc.mutation.UserID(); ok {
		_spec.SetField(blacklist.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := bc.mutation.Reason(); ok {
		_spec.SetField(blacklist.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := bc.mutation.CreatedAt(); ok {
		_spec.SetField(blacklist.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := bc.mutation.UpdatedAt(); ok {
		_spec.SetField(blacklist.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Blacklist.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BlacklistUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (bc *BlacklistCreate) OnConflict(opts ...sql.ConflictOption) *BlacklistUpsertOne {
	bc.conflict = opts
	return &BlacklistUpsertOne{
		create: bc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Blacklist.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (bc *BlacklistCreate) OnConflictColumns(columns ...string) *BlacklistUpsertOne {
	bc.conflict = append(bc.conflict, sql.ConflictColumns(columns...))
	return &BlacklistUpsertOne{
		create: bc,
	}
}

type (
	// BlacklistUpsertOne is the builder for "upsert"-ing
	//  one Blacklist node.
	BlacklistUpsertOne struct {
		create *BlacklistCreate
	}

	// BlacklistUpsert is the "OnConflict" setter.
	BlacklistUpsert struct {
		*sql.UpdateSet
	}
)

// SetReason sets the "reason" field.
func (u *BlacklistUpsert) SetReason(v string) *BlacklistUpsert {
	u.Set(blacklist.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *BlacklistUpsert) UpdateReason() *BlacklistUpsert {
	u.SetExcluded(blacklist.FieldReason)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BlacklistUpsert) SetUpdatedAt(v time.Time) *BlacklistUpsert {
	u.Set(blacklist.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BlacklistUpsert) UpdateUpdatedAt() *BlacklistUpsert {
	u.SetExcluded(blacklist.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Blacklist.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BlacklistUpsertOne) UpdateNewValues() *BlacklistUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(blacklist.FieldUserID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(blacklist.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Blacklist.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BlacklistUpsertOne) Ignore() *BlacklistUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BlacklistUpsertOne) DoNothing() *BlacklistUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BlacklistCreate.OnConflict
// documentation for more info.
func (u *BlacklistUpsertOne) Update(set func(*BlacklistUpsert)) *BlacklistUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BlacklistUpsert{UpdateSet: update})
	}))
	return u
}

// SetReason sets the "reason" field.
func (u *BlacklistUpsertOne) SetReason(v string) *BlacklistUpsertOne {
	return u.Update(func(s *BlacklistUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *BlacklistUpsertOne) UpdateReason() *BlacklistUpsertOne {
	return u.Update(func(s *BlacklistUpsert) {
		s.UpdateReason()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BlacklistUpsertOne) SetUpdatedAt(v time.Time) *BlacklistUpsertOne {
	return u.Update(func(s *BlacklistUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BlacklistUpsertOne) UpdateUpdatedAt() *BlacklistUpsertOne {
	return u.Update(func(s *BlacklistUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BlacklistUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BlacklistCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BlacklistUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BlacklistUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BlacklistUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BlacklistCreateBulk is the builder for creating many Blacklist entities in bulk.
type BlacklistCreateBulk struct {
	config
	err      error
	builders []*BlacklistCreate
	conflict []sql.ConflictOption
}

// Save creates the Blacklist entities in the database.
func (bcb *BlacklistCreateBulk) Save(ctx context.Context) ([]*Blacklist, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Blacklist, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BlacklistMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = bcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BlacklistCreateBulk) SaveX(ctx context.Context) []*Blacklist {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BlacklistCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BlacklistCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Blacklist.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BlacklistUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (bcb *BlacklistCreateBulk) OnConflict(opts ...sql.ConflictOption) *BlacklistUpsertBulk {
	bcb.conflict = opts
	return &BlacklistUpsertBulk{
		create: bcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Blacklist.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (bcb *BlacklistCreateBulk) OnConflictColumns(columns ...string) *BlacklistUpsertBulk {
	bcb.conflict = append(bcb.conflict, sql.ConflictColumns(columns...))
	return &BlacklistUpsertBulk{
		create: bcb,
	}
}

// BlacklistUpsertBulk is the builder for "upsert"-ing
// a bulk of Blacklist nodes.
type BlacklistUpsertBulk struct {
	create *BlacklistCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Blacklist.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BlacklistUpsertBulk) UpdateNewValues() *BlacklistUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(blacklist.FieldUserID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(blacklist.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Blacklist.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BlacklistUpsertBulk) Ignore() *BlacklistUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BlacklistUpsertBulk) DoNothing() *BlacklistUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BlacklistCreateBulk.OnConflict
// documentation for more info.
func (u *BlacklistUpsertBulk) Update(set func(*BlacklistUpsert)) *BlacklistUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BlacklistUpsert{UpdateSet: update})
	}))
	return u
}

// SetReason sets the "reason" field.
func (u *BlacklistUpsertBulk) SetReason(v string) *BlacklistUpsertBulk {
	return u.Update(func(s *BlacklistUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *BlacklistUpsertBulk) UpdateReason() *BlacklistUpsertBulk {
	return u.Update(func(s *BlacklistUpsert) {
		s.UpdateReason()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BlacklistUpsertBulk) SetUpdatedAt(v time.Time) *BlacklistUpsertBulk {
	return u.Update(func(s *BlacklistUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BlacklistUpsertBulk) UpdateUpdatedAt() *BlacklistUpsertBulk {
	return u.Update(func(s *BlacklistUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BlacklistUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BlacklistCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BlacklistCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BlacklistUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
