// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/taythebot/discord_chatbot/ent/blacklist"
	"github.com/taythebot/discord_chatbot/ent/channel"
	"github.com/taythebot/discord_chatbot/ent/guild"
	"github.com/taythebot/discord_chatbot/ent/message"
	"github.com/taythebot/discord_chatbot/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blacklistFields := schema.Blacklist{}.Fields()
	_ = blacklistFields
	// blacklistDescUserID is the schema descriptor for user_id field.
	blacklistDescUserID := blacklistFields[0].Descriptor()
	// blacklist.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	blacklist.UserIDValidator = blacklistDescUserID.Validators[0].(func(string) error)
	// blacklistDescReason is the schema descriptor for reason field.
	blacklistDescReason := blacklistFields[1].Descriptor()
	// blacklist.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	blacklist.ReasonValidator = blacklistDescReason.Validators[0].(func(string) error)
	// blacklistDescCreatedAt is the schema descriptor for created_at field.
	blacklistDescCreatedAt := blacklistFields[2].Descriptor()
	// blacklist.DefaultCreatedAt holds the default value on creation for the created_at field.
	blacklist.DefaultCreatedAt = blacklistDescCreatedAt.Default.(func() time.Time)
	// blacklistDescUpdatedAt is the schema descriptor for updated_at field.
	blacklistDescUpdatedAt := blacklistFields[3].Descriptor()
	// blacklist.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	blacklist.DefaultUpdatedAt = blacklistDescUpdatedAt.Default.(func() time.Time)
	// blacklist.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	blacklist.UpdateDefaultUpdatedAt = blacklistDescUpdatedAt.UpdateDefault.(func() time.Time)
	channelFields := schema.Channel{}.Fields()
	_ = channelFields
	// channelDescName is the schema descriptor for name field.
	channelDescName := channelFields[1].Descriptor()
	// channel.NameValidator is a validator for the "name" field. It is called by the builders before save.
	channel.NameValidator = channelDescName.Validators[0].(func(string) error)
	// channelDescModel is the schema descriptor for model field.
	channelDescModel := channelFields[2].Descriptor()
	// channel.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	channel.ModelValidator = channelDescModel.Validators[0].(func(string) error)
	// channelDescPrompt is the schema descriptor for prompt field.
	channelDescPrompt := channelFields[3].Descriptor()
	// channel.PromptValidator is a validator for the "prompt" field. It is called by the builders before save.
	channel.PromptValidator = channelDescPrompt.Validators[0].(func(string) error)
	// channelDescGuildID is the schema descriptor for guild_id field.
	channelDescGuildID := channelFields[4].Descriptor()
	// channel.GuildIDValidator is a validator for the "guild_id" field. It is called by the builders before save.
	channel.GuildIDValidator = channelDescGuildID.Validators[0].(func(string) error)
	// channelDescCreatedAt is the schema descriptor for created_at field.
	channelDescCreatedAt := channelFields[5].Descriptor()
	// channel.DefaultCreatedAt holds the default value on creation for the created_at field.
	channel.DefaultCreatedAt = channelDescCreatedAt.Default.(func() time.Time)
	// channelDescUpdatedAt is the schema descriptor for updated_at field.
	channelDescUpdatedAt := channelFields[6].Descriptor()
	// channel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	channel.DefaultUpdatedAt = channelDescUpdatedAt.Default.(func() time.Time)
	// channel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	channel.UpdateDefaultUpdatedAt = channelDescUpdatedAt.UpdateDefault.(func() time.Time)
	// channelDescID is the schema descriptor for id field.
	channelDescID := channelFields[0].Descriptor()
	// channel.IDValidator is a validator for the "id" field. It is called by the builders before save.
	channel.IDValidator = channelDescID.Validators[0].(func(string) error)
	guildFields := schema.Guild{}.Fields()
	_ = guildFields
	// guildDescName is the schema descriptor for name field.
	guildDescName := guildFields[1].Descriptor()
	// guild.NameValidator is a validator for the "name" field. It is called by the builders before save.
	guild.NameValidator = guildDescName.Validators[0].(func(string) error)
	// guildDescActive is the schema descriptor for active field.
	guildDescActive := guildFields[2].Descriptor()
	// guild.DefaultActive holds the default value on creation for the active field.
	guild.DefaultActive = guildDescActive.Default.(bool)
	// guildDescCreatedAt is the schema descriptor for created_at field.
	guildDescCreatedAt := guildFields[3].Descriptor()
	// guild.DefaultCreatedAt holds the default value on creation for the created_at field.
	guild.DefaultCreatedAt = guildDescCreatedAt.Default.(func() time.Time)
	// guildDescUpdatedAt is the schema descriptor for updated_at field.
	guildDescUpdatedAt := guildFields[4].Descriptor()
	// guild.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	guild.DefaultUpdatedAt = guildDescUpdatedAt.Default.(func() time.Time)
	// guild.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	guild.UpdateDefaultUpdatedAt = guildDescUpdatedAt.UpdateDefault.(func() time.Time)
	// guildDescID is the schema descriptor for id field.
	guildDescID := guildFields[0].Descriptor()
	// guild.IDValidator is a validator for the "id" field. It is called by the builders before save.
	guild.IDValidator = guildDescID.Validators[0].(func(string) error)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescContent is the schema descriptor for content field.
	messageDescContent := messageFields[3].Descriptor()
	// message.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	message.ContentValidator = messageDescContent.Validators[0].(func(string) error)
	// messageDescChannelID is the schema descriptor for channel_id field.
	messageDescChannelID := messageFields[4].Descriptor()
	// message.ChannelIDValidator is a validator for the "channel_id" field. It is called by the builders before save.
	message.ChannelIDValidator = messageDescChannelID.Validators[0].(func(string) error)
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[5].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
}
