// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Blacklist is the predicate function for blacklist builders.
type Blacklist func(*sql.Selector)

// Channel is the predicate function for channel builders.
type Channel func(*sql.Selector)

// Guild is the predicate function for guild builders.
type Guild func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)
